services:
  dbservice:
    image: mysql:latest
    container_name: springboot jobportaldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobportal
    volumes:
        - D:\SpringBootDev\jobportal\jobportal:/var/lib/msql